directories:
  output: ../release
  buildResources: resources
appId: com.attendance.ats
productName: ATS Desktop
files:
  - filter:
      - ../client/dist/**/*
      - main.js
      - preload.js
      - ../server/web-api/**/*
mac:
  target:
    - dmg
win:
  target:
    - nsis
electronVersion: 26.6.10
